forge "https://forge.puppetlabs.com"

mod 'apt',
  :git => "https://github.com/puppetlabs/puppetlabs-apt"

mod 'stdlib',
  :git => "https://github.com/puppetlabs/puppetlabs-stdlib"

mod 'concat',
  :git => "https://github.com/puppetlabs/puppetlabs-concat"
  
mod "nginx",
  :git => "git://github.com/jfryman/puppet-nginx.git"