forge "https://forge.puppetlabs.com"

mod 'apt',
  :git => "https://github.com/puppetlabs/puppetlabs-apt"

mod 'stdlib',
  :git => "https://github.com/puppetlabs/puppetlabs-stdlib"

mod 'concat',
  :git => "https://github.com/puppetlabs/puppetlabs-concat"
  
mod "nginx",
  :git => "https://github.com/jfryman/puppet-nginx"
  
mod "postgresql",
  :git => "https://github.com/puppetlabs/puppetlabs-postgresql"